name: HealthSync CI - Build 1.3.000
on:
  push:
    branches:
      - health-sync-dev-1.3
  pull_request:
    branches:
      - health-sync-dev-1.3

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npm install dotenv jsonwebtoken cors nodemon

      - name: Create data.json with perms
        run: |
          touch data.json
          chmod 666 data.json

      - name: Set up .env
        run: |
          echo "PORT=3000" > .env
          echo "DATA_PATH=$(pwd)/data.json" >> .env
          echo "JWT_SECRET=your-secret-key" >> .env

      - name: Run lint and tests (placeholder)
        run: |
          # Add lint/test scripts in package.json later
          echo "Lint and tests TBD - placeholder"
          npm start &  # Start server in background
          sleep 5      # Wait for server

      - name: Test /api/login
        run: |
          curl -X POST http://localhost:3000/api/login -H "Content-Type: application/json" -d '{"username":"testuser","password":"testpass"}' -f || exit 1

      - name: Test /api/data POST
        run: |
          curl -X POST http://localhost:3000/api/data -H "Content-Type: application/json" -H "Authorization: Bearer $(curl -s -X POST http://localhost:3000/api/login -H 'Content-Type: application/json' -d '{\"username\":\"testuser\",\"password\":\"testpass\"}' | jq -r '.token')" -d '{"test":"data"}' -f || exit 1

      - name: Test /api/data GET
        run: |
          curl -X GET http://localhost:3000/api/data -H "Authorization: Bearer $(curl -s -X POST http://localhost:3000/api/login -H 'Content-Type: application/json' -d '{\"username\":\"testuser\",\"password\":\"testpass\"}' | jq -r '.token')" -f || exit 1