# HealthSync Version 1.2.3 - GitHub Actions Deployment Workflow
name: Deploy HealthSync

on:
  push:
    branches:
      - main
      - health-sync-1.2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }} # Add custom port as a secret
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem -p $SSH_PORT ${SERVER_USER}@${SERVER_IP} << 'EOF'
            cd /Users/ericclapton/Documents/code_sp/HealthSync
            git pull origin main
            npm install
            npm restart
            echo "Deployment complete"
          EOF
          rm private_key.pem
